### PR TITLE
Us503

### PR DESCRIPTION
**Pull request by SDET222**

### CODE REVIEW

**Review by kgasimov — CHANGES_REQUESTED** [review]
please some more lines

**Comment by SDET222** [comment]
ok

**Review by kgasimov — CHANGES_REQUESTED** [review]
can/t see new lines of code

**Comment by SDET222** [comment]
give me a sec

**Review by kgasimov — APPROVED** [review]
good job!

**Review by kgasimov — APPROVED** [review]
Good job! Approved

**Pull request merged**
